spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rajje.db.elephantsql.com:5432/syabkhtb
    username: syabkhtb
    password: J7LXI5pNQ_UoUP316yEd-yoXnCOZK8HE
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
security:
  oauth2:
    client:
      registration:
        google:
          client-id: 540979386958-g0je0rt8f1pr1ovp5ati0iuku5424a17.apps.googleusercontent.com
          client-secret: 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
          scope:
            - email
            - profile
            - name

logging:
  level:
    org.springframework: info
    org.hibernate: info

server:
  port: 8000